#!/bin/bash
yes yes | python /var/www/plase/manage.py collectstatic
if [ -a /var/www/plase/plase.pid ]; then cat /var/www/plase/plase.pid | xargs kill; fi
python /var/www/plase/manage.py runfcgi method=threaded host=127.0.0.1 port=8080 pidfile=/var/www/plase/plase.pid
